import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from '@/components/navigation';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${inter.className} min-h-screen bg-gray-200`}>
        <Navigation />
        <main className="container mx-auto px-4">{children}</main>
      </body>
    </html>
  );
}
