export function Footer() {
  return (
    <footer className="border-t">
      <div className="container mx-auto px-4 py-6">
        <p className="text-center text-sm text-muted-foreground">
          © {new Date().getFullYear()} Copyright kodak, All Rights Reserved.
        </p>
        <p className="text-center text-sm text-muted-foreground">
          Site generated by Next.js.
        </p>
      </div>
    </footer>
  );
}
